export const roles = [
  { key: 'superAdmin', label: '超级管理员', group: '总部' },
  { key: 'operations', label: '总部运营', group: '总部' },
  { key: 'delivery', label: '交付负责人', group: '交付中心' },
  { key: 'tutor', label: '导学师', group: '交付中心' },
  { key: 'studentManager', label: '学管师', group: '交付中心' },
  { key: 'planner', label: '规划师', group: '交付中心' },
  { key: 'qualityControl', label: '质控专员', group: '总部' },
  { key: 'customerService', label: '客服', group: '交付中心' },
  { key: 'merchant', label: '商家负责人', group: '商家' },
  { key: 'finance', label: '财务人员', group: '总部' },
  { key: 'partnerAuditor', label: '合作审核员', group: '总部' }
]

export const deliveryCenterOptions = [
  { id: 'center-hq', name: '总部交付中心', capacity: '可接收 12 人', response: '预计 20 分钟响应', recommended: true },
  { id: 'center-east', name: '华东交付中心', capacity: '可接收 8 人', response: '预计 35 分钟响应', recommended: false },
  { id: 'center-south', name: '华南交付中心', capacity: '可接收 5 人', response: '预计 1 小时响应', recommended: false }
]

export const teacherOptions = [
  {
    id: 'teacher-shen',
    name: '沈老师',
    center: '总部交付中心',
    subject: '数学',
    grade: '高中',
    match: 96,
    rating: '4.9',
    workload: '本周 12 节',
    slots: ['今天 14:00', '今天 16:00', '明天 10:00']
  },
  {
    id: 'teacher-zhou',
    name: '周老师',
    center: '总部交付中心',
    subject: '数学',
    grade: '高中',
    match: 91,
    rating: '4.8',
    workload: '本周 15 节',
    slots: ['今天 15:30', '明天 14:00', '周六 10:00']
  },
  {
    id: 'teacher-su',
    name: '苏老师',
    center: '华东交付中心',
    subject: '英语',
    grade: '初中',
    match: 89,
    rating: '4.9',
    workload: '本周 10 节',
    slots: ['今天 16:00', '明天 09:00', '周六 14:00']
  },
  {
    id: 'teacher-lu',
    name: '陆老师',
    center: '华东交付中心',
    subject: '物理',
    grade: '高中',
    match: 94,
    rating: '4.8',
    workload: '本周 11 节',
    slots: ['今天 17:00', '明天 15:30', '周六 16:00']
  }
]

export const roleStats = {
  superAdmin: [
    { key: 'system-risk', label: '全局风险', value: '11', meta: '跨模块待确认', tone: 'red', view: 'system' },
    { key: 'pending-order', label: '订单异常', value: '12', meta: '4 条已超时', tone: 'blue', view: 'orders' },
    { key: 'pending-delivery', label: '交付异常', value: '28', meta: '缺教师 2 条', tone: 'cyan', view: 'delivery' },
    { key: 'pending-finance', label: '结算异常', value: '3', meta: '差额 ¥ 1,280', tone: 'amber', view: 'finance' },
    { key: 'today-income', label: '今日回款', value: '¥ 96,579', meta: '目标完成 78%', tone: 'green', view: 'analytics' }
  ],
  operations: [
    { key: 'pending-order', label: '待处理订单', value: '12', meta: '4 条已超时', tone: 'blue', view: 'orders' },
    { key: 'pending-review', label: '待审核入驻', value: '6', meta: '最早等待 3 小时', tone: 'amber', view: 'partners' },
    { key: 'pending-schedule', label: '待分配排课', value: '28', meta: '较昨日 +5', tone: 'cyan', view: 'delivery' },
    { key: 'exceptions', label: '业务异常', value: '4', meta: '需要今天处理', tone: 'red', view: 'orders' },
    { key: 'today-income', label: '今日回款', value: '¥ 96,579', meta: '目标完成 78%', tone: 'green', view: 'analytics' }
  ],
  delivery: [
    { key: 'pending-dispatch', label: '待分配学员', value: '18', meta: '3 人临近超时', tone: 'blue', view: 'delivery' },
    { key: 'pending-schedule', label: '待排课程', value: '10', meta: '今天需完成', tone: 'amber', view: 'delivery' },
    { key: 'today-class', label: '今日上课', value: '86', meta: '7 个交付中心', tone: 'cyan', view: 'delivery' },
    { key: 'delivery-risk', label: '交付异常', value: '3', meta: '缺教师 2 条', tone: 'red', view: 'delivery' },
    { key: 'consume', label: '今日消课', value: '214', meta: '完成率 92%', tone: 'green', view: 'analytics' }
  ],
  tutor: [
    { key: 'today-class', label: '今日课程', value: '6', meta: '下一节 14:00', tone: 'blue', view: 'delivery' },
    { key: 'pending-class', label: '待上课', value: '2', meta: '1 节需确认教案', tone: 'cyan', view: 'delivery' },
    { key: 'pending-record', label: '待录学情', value: '3', meta: '课后 2 小时内完成', tone: 'amber', view: 'delivery' },
    { key: 'student-risk', label: '学员预警', value: '2', meta: '连续缺课/低评价', tone: 'red', view: 'delivery' },
    { key: 'consume', label: '本周已消课', value: '18', meta: '完成率 94%', tone: 'green', view: 'delivery' }
  ],
  studentManager: [
    { key: 'pending-schedule', label: '待排课', value: '10', meta: '3 人临近超时', tone: 'blue', view: 'delivery' },
    { key: 'consume-approval', label: '核销待审批', value: '7', meta: '最早等待 4 小时', tone: 'amber', view: 'delivery' },
    { key: 'renewal-risk', label: '续费风险', value: '14', meta: '7 天内课时不足', tone: 'red', view: 'delivery' },
    { key: 'family-followup', label: '家长待沟通', value: '8', meta: '2 人超过 24 小时', tone: 'cyan', view: 'delivery' },
    { key: 'active-student', label: '在读学员', value: '286', meta: '本中心', tone: 'green', view: 'registry-learning' }
  ],
  planner: [
    { key: 'first-followup', label: '待首追', value: '12', meta: '4 人将在 2 小时内超时', tone: 'blue', view: 'delivery' },
    { key: 'following', label: '跟进中', value: '28', meta: '今日需回访 9 人', tone: 'cyan', view: 'delivery' },
    { key: 'quote', label: '待出题单', value: '6', meta: '体验课已完成', tone: 'amber', view: 'orders' },
    { key: 'dispatch', label: '待转正分单', value: '5', meta: '已确认购买意向', tone: 'red', view: 'delivery' },
    { key: 'conversion', label: '本月转正率', value: '42.8%', meta: '较上月 +3.6%', tone: 'green', view: 'analytics' }
  ],
  qualityControl: [
    { key: 'pending-review', label: '待质检课堂', value: '16', meta: '4 节今日到期', tone: 'blue', view: 'delivery' },
    { key: 'first-four', label: '前四课必检', value: '7', meta: '覆盖 5 名新学员', tone: 'cyan', view: 'delivery' },
    { key: 'rectification', label: '整改待复核', value: '5', meta: '2 项已超时', tone: 'red', view: 'delivery' },
    { key: 'report', label: '待出质控报告', value: '4', meta: '本周批次', tone: 'amber', view: 'analytics' },
    { key: 'average-score', label: '课堂均分', value: '91.6', meta: '较上周 +1.2', tone: 'green', view: 'analytics' }
  ],
  customerService: [
    { key: 'pending-reply', label: '家长待回复', value: '18', meta: '3 条超过 30 分钟', tone: 'blue', view: 'delivery' },
    { key: 'pending-ticket', label: '待处理工单', value: '9', meta: '投诉 2 / 售后 7', tone: 'amber', view: 'orders' },
    { key: 'group-alert', label: '服务群预警', value: '6', meta: '4 个群长时间未响应', tone: 'red', view: 'delivery' },
    { key: 'refund-followup', label: '退费协调', value: '3', meta: '等待业务确认', tone: 'cyan', view: 'finance' },
    { key: 'closed-ticket', label: '今日已结案', value: '24', meta: '一次解决率 87%', tone: 'green', view: 'delivery' }
  ],
  merchant: [
    { key: 'follow-up', label: '待跟进学员', value: '8', meta: '2 人超过 24 小时', tone: 'blue', view: 'delivery' },
    { key: 'pending-pay', label: '待支付订单', value: '5', meta: '合计 ¥ 18,400', tone: 'amber', view: 'orders' },
    { key: 'pending-class', label: '待排课', value: '6', meta: '本周需完成', tone: 'cyan', view: 'delivery' },
    { key: 'service-risk', label: '服务异常', value: '2', meta: '待总部协助', tone: 'red', view: 'delivery' },
    { key: 'withdrawable', label: '可提现', value: '¥ 10,400', meta: '下次结算 07/05', tone: 'green', view: 'finance' }
  ],
  finance: [
    { key: 'pending-receipt', label: '收款确认', value: '9', meta: '含 2 笔线下转账', tone: 'blue', view: 'orders' },
    { key: 'pending-bill', label: '待确认账单', value: '12', meta: '合计 ¥ 286,400', tone: 'amber', view: 'finance' },
    { key: 'diff-bill', label: '差额账单', value: '3', meta: '差额 ¥ 1,280', tone: 'red', view: 'finance' },
    { key: 'purchase-pay', label: '采购付款', value: '6', meta: '2 单缺凭证', tone: 'cyan', view: 'purchase' },
    { key: 'paid-month', label: '本月已结', value: '¥ 2.86m', meta: '较上月 +12.4%', tone: 'green', view: 'analytics' }
  ],
  partnerAuditor: [
    { key: 'pending-review', label: '待初审', value: '6', meta: '最早等待 3 小时', tone: 'blue', view: 'partners' },
    { key: 'supplement', label: '待补充', value: '3', meta: '资料完整度低于 80%', tone: 'amber', view: 'partners' },
    { key: 'license-risk', label: '证照预警', value: '1', meta: '12 天后到期', tone: 'red', view: 'partners' },
    { key: 'contract', label: '待生效合约', value: '4', meta: '本周需确认', tone: 'cyan', view: 'registry-partner-center' },
    { key: 'active-partner', label: '合作中', value: '248', meta: '本月新增 12', tone: 'green', view: 'registry-partner-center' }
  ]
}

export const workbenchTasks = [
  {
    id: 'TASK-2401',
    title: '核验支付异常订单',
    category: '订单',
    subject: '订单 ZL5280****1280',
    priority: '紧急',
    due: '今天 11:30',
    owner: '总部运营',
    status: '待处理',
    view: 'orders',
    kind: 'order',
    targetId: 'order-1',
    roleKeys: ['superAdmin', 'operations', 'finance', 'customerService']
  },
  {
    id: 'TASK-2402',
    title: '为正式课学员分配教师',
    category: '交付',
    subject: '陈同学 / 高中一年级 / 数学正式课',
    priority: '高',
    due: '今天 14:00',
    owner: '交付一组',
    status: '待分配',
    view: 'delivery',
    kind: 'delivery',
    targetId: 'delivery-1',
    roleKeys: ['superAdmin', 'operations', 'delivery', 'studentManager']
  },
  {
    id: 'TASK-2403',
    title: '审核新商家入驻资料',
    category: '合作',
    subject: '杭州青禾教育',
    priority: '普通',
    due: '今天 17:00',
    owner: '合作中心',
    status: '待审核',
    view: 'partners',
    kind: 'partner',
    targetId: 'partner-1',
    roleKeys: ['superAdmin', 'operations', 'partnerAuditor']
  },
  {
    id: 'TASK-2404',
    title: '补充采购单付款凭证',
    category: '采购',
    subject: '采购单 XCG2606260049 / 教学平板',
    priority: '普通',
    due: '明天 10:00',
    owner: '财务组',
    status: '待补充',
    view: 'purchase',
    kind: 'purchase',
    targetId: 'purchase-2',
    roleKeys: ['superAdmin', 'operations', 'finance', 'merchant']
  },
  {
    id: 'TASK-2405',
    title: '处理排课时间冲突',
    category: '交付',
    subject: '王同学 / 今天 15:30 / 物理',
    priority: '高',
    due: '今天 15:30',
    owner: '交付二组',
    status: '有冲突',
    view: 'delivery',
    kind: 'delivery',
    targetId: 'delivery-3',
    roleKeys: ['superAdmin', 'operations', 'delivery', 'studentManager']
  },
  {
    id: 'TASK-2406',
    title: '补录课后学情与课堂报告',
    category: '授课',
    subject: '赵同学 / 初三数学 / 第 19 课',
    priority: '高',
    due: '今天 12:00',
    owner: '周老师',
    status: '待录学情',
    view: 'delivery',
    kind: 'delivery',
    targetId: 'delivery-4',
    roleKeys: ['superAdmin', 'delivery', 'tutor']
  },
  {
    id: 'TASK-2407',
    title: '完成体验课首追与学习方案',
    category: '转化',
    subject: '刘同学 / 高中英语体验课',
    priority: '紧急',
    due: '今天 11:00',
    owner: '规划组',
    status: '待首追',
    view: 'delivery',
    kind: 'delivery',
    targetId: 'delivery-6',
    roleKeys: ['superAdmin', 'delivery', 'planner']
  },
  {
    id: 'TASK-2408',
    title: '回看课堂录像并完成五维评分',
    category: '质控',
    subject: '赵同学 / 初三数学 / 第 18 课',
    priority: '高',
    due: '今天 16:00',
    owner: '质控组',
    status: '待质检',
    view: 'delivery',
    kind: 'delivery',
    targetId: 'delivery-4',
    roleKeys: ['superAdmin', 'qualityControl']
  },
  {
    id: 'TASK-2409',
    title: '跟进家长投诉并更新处理记录',
    category: '客服',
    subject: '王同学 / 排课冲突投诉',
    priority: '紧急',
    due: '今天 10:30',
    owner: '客服组',
    status: '待回复',
    view: 'delivery',
    kind: 'delivery',
    targetId: 'delivery-3',
    roleKeys: ['superAdmin', 'delivery', 'customerService']
  },
  {
    id: 'TASK-2410',
    title: '联系家长确认续费意向',
    category: '学管',
    subject: '周同学 / 剩余 2 课时',
    priority: '高',
    due: '今天 18:00',
    owner: '学管组',
    status: '待沟通',
    view: 'delivery',
    kind: 'delivery',
    targetId: 'delivery-5',
    roleKeys: ['superAdmin', 'delivery', 'studentManager']
  },
  {
    id: 'TASK-2411',
    title: '跟进本商家学员付款',
    category: '订单',
    subject: '陈同学 / 高中数学正式课',
    priority: '高',
    due: '今天 13:30',
    owner: '杭州青禾教育',
    status: '待跟进',
    view: 'orders',
    kind: 'order',
    targetId: 'order-1',
    roleKeys: ['superAdmin', 'merchant']
  }
]

export const exceptions = [
  { id: 'EX-01', title: '4 笔订单支付状态不同步', meta: '最长已持续 2 小时', tone: 'red', view: 'orders', roleKeys: ['superAdmin', 'operations', 'finance', 'customerService'] },
  { id: 'EX-02', title: '2 名学员本周暂无可用教师', meta: '需要跨中心调配', tone: 'amber', view: 'delivery', roleKeys: ['superAdmin', 'operations', 'delivery', 'studentManager'] },
  { id: 'EX-03', title: '1 份入驻资料证照即将过期', meta: '营业执照剩余 12 天', tone: 'amber', view: 'partners', roleKeys: ['superAdmin', 'operations', 'partnerAuditor'] },
  { id: 'EX-04', title: '财务结算差额待核对', meta: '差额 ¥ 320.00', tone: 'blue', view: 'finance', roleKeys: ['superAdmin', 'finance', 'merchant'] },
  { id: 'EX-05', title: '3 份课后学情超过录入时限', meta: '影响家长课后反馈', tone: 'amber', view: 'delivery', roleKeys: ['superAdmin', 'delivery', 'tutor'] },
  { id: 'EX-06', title: '2 名学员续费沟通即将超时', meta: '剩余课时低于 3 节', tone: 'red', view: 'delivery', roleKeys: ['superAdmin', 'delivery', 'studentManager'] },
  { id: 'EX-07', title: '4 名体验课学员尚未首追', meta: '最早已等待 95 分钟', tone: 'red', view: 'delivery', roleKeys: ['superAdmin', 'delivery', 'planner'] },
  { id: 'EX-08', title: '2 项课堂整改已超过复核时限', meta: '涉及教学反馈与作业布置', tone: 'red', view: 'delivery', roleKeys: ['superAdmin', 'qualityControl'] },
  { id: 'EX-09', title: '4 个家长服务群长时间未响应', meta: '最长 42 分钟', tone: 'amber', view: 'delivery', roleKeys: ['superAdmin', 'delivery', 'customerService'] }
]

export const flowStages = [
  { label: '新订单', value: 36, meta: '今日' },
  { label: '已支付', value: 29, meta: '转化 81%' },
  { label: '已分单', value: 24, meta: '待处理 5' },
  { label: '交付中', value: 18, meta: '异常 2' },
  { label: '已完成', value: 14, meta: '完成率 58%' }
]

export const ordersSeed = [
  {
    id: 'order-1',
    orderNo: 'ZL52809199884812',
    status: '待支付',
    dealer: '杭州青禾教育',
    seller: '总部商城',
    orderingDealer: '--',
    plannerRequirement: '手动指定',
    source: '线上订单',
    platform: '小程序',
    batch: '202606-A',
    orderMethod: '家长',
    parentName: '陈家长',
    parentMobile: '138****2817',
    dealerReferrer: '陈老师',
    courseType: '正式课',
    studentName: '陈同学',
    channel: '线上商城',
    courseName: '高中数学正式课 40 课时',
    amount: '¥ 12,800',
    paidAmount: '¥ 12,800',
    paymentTransactionNo: '20260627****8621',
    logisticsNo: '--',
    allocationStatus: '未分配',
    deliveryCenter: '--',
    hasPad: '否',
    firstPurchase: '是',
    orderTime: '2026-06-27 09:26',
    orderRemark: '家长希望工作日晚间上课',
    riskStatus: '支付状态异常',
    afterSaleStatus: '--',
    nextAction: '核验支付',
    payment: {
      transactionNo: '20260627****8621',
      channel: '支付宝',
      amount: '¥ 12,800',
      paidAt: '06-27 09:27',
      systemStatus: '支付成功',
      orderStatus: '未支付'
    },
    history: [
      { time: '09:31', title: '系统识别支付异常', detail: '支付流水成功，但订单仍为未支付' },
      { time: '09:26', title: '订单创建', detail: '来源：线上商城' }
    ]
  },
  {
    id: 'order-2',
    orderNo: 'ZL52805925401750',
    status: '已支付',
    dealer: '华东渠道中心',
    seller: '总部商城',
    orderingDealer: '--',
    plannerRequirement: '不需要',
    source: '线上订单',
    platform: '小程序',
    batch: '202606-A',
    orderMethod: '家长',
    parentName: '张家长',
    parentMobile: '186****0932',
    dealerReferrer: '--',
    courseType: '体验课',
    studentName: '张同学',
    channel: '渠道推广',
    courseName: '初中英语体验课',
    amount: '¥ 99',
    paidAmount: '¥ 99',
    paymentTransactionNo: '20260627****1750',
    logisticsNo: '--',
    allocationStatus: '未分配',
    deliveryCenter: '--',
    hasPad: '否',
    firstPurchase: '是',
    orderTime: '2026-06-27 09:10',
    orderRemark: '--',
    riskStatus: '--',
    afterSaleStatus: '--',
    nextAction: '分配中心',
    history: [{ time: '09:10', title: '订单创建并完成支付', detail: '等待分配交付中心' }]
  },
  {
    id: 'order-3',
    orderNo: 'ZL52804736554803',
    status: '已支付',
    dealer: '成都星途成长中心',
    seller: '智鹿总部',
    orderingDealer: '成都星途成长中心',
    plannerRequirement: '手动指定',
    source: '手动导入',
    platform: '录入',
    batch: '202606-B',
    orderMethod: '代下单',
    parentName: '王家长',
    parentMobile: '150****6721',
    dealerReferrer: '刘老师',
    courseType: '正式课',
    studentName: '王同学',
    channel: '商家录单',
    courseName: '高中物理正式课 60 课时',
    amount: '¥ 7,400',
    paidAmount: '¥ 7,400',
    paymentTransactionNo: 'OFFLINE-20260627-0038',
    logisticsNo: 'SF****6812',
    allocationStatus: '已分配',
    deliveryCenter: '华东交付中心',
    hasPad: '是',
    firstPurchase: '否',
    orderTime: '2026-06-27 08:54',
    orderRemark: '含学习平板，分开发货',
    riskStatus: '--',
    afterSaleStatus: '--',
    nextAction: '确认物流',
    history: [{ time: '08:58', title: '订单已分配', detail: '华东交付中心' }]
  },
  {
    id: 'order-4',
    orderNo: 'ZL52792542283656',
    status: '已支付',
    dealer: '总部直营',
    seller: '总部商城',
    orderingDealer: '--',
    plannerRequirement: '手动指定',
    source: '线上订单',
    platform: '小程序',
    batch: '202606-A',
    orderMethod: '家长',
    parentName: '赵家长',
    parentMobile: '177****4380',
    dealerReferrer: '--',
    courseType: '正式课',
    studentName: '赵同学',
    channel: '线上商城',
    courseName: '初中数学正式课 40 课时',
    amount: '¥ 18,600',
    paidAmount: '¥ 18,600',
    paymentTransactionNo: '20260626****3656',
    logisticsNo: '--',
    allocationStatus: '已分配',
    deliveryCenter: '总部交付中心',
    hasPad: '否',
    firstPurchase: '是',
    orderTime: '2026-06-26 18:42',
    orderRemark: '--',
    riskStatus: '--',
    afterSaleStatus: '--',
    nextAction: '查看进度',
    history: [{ time: '19:02', title: '进入正式课交付', detail: '总部交付中心' }]
  },
  {
    id: 'order-5',
    orderNo: 'ZL52791995963816',
    status: '待支付',
    dealer: '杭州青禾教育',
    seller: '杭州青禾教育',
    orderingDealer: '杭州青禾教育',
    plannerRequirement: '不需要',
    source: '手动导入',
    platform: '录入',
    batch: '202606-B',
    orderMethod: '代下单',
    parentName: '周家长',
    parentMobile: '159****9074',
    dealerReferrer: '陈老师',
    courseType: '正式课',
    studentName: '周同学',
    channel: '商家录单',
    courseName: '初中数学正式课 30 课时',
    amount: '¥ 9,600',
    paidAmount: '¥ 0',
    paymentTransactionNo: '--',
    logisticsNo: '--',
    allocationStatus: '未分配',
    deliveryCenter: '--',
    hasPad: '否',
    firstPurchase: '否',
    orderTime: '2026-06-26 17:20',
    orderRemark: '等待家长付款',
    riskStatus: '--',
    afterSaleStatus: '--',
    nextAction: '提醒支付',
    history: [{ time: '17:20', title: '订单录入', detail: '等待家长付款' }]
  },
  {
    id: 'order-6',
    orderNo: 'ZL52780547298992',
    status: '已支付',
    dealer: '华南渠道中心',
    seller: '总部商城',
    orderingDealer: '--',
    plannerRequirement: '不需要',
    source: '线上订单',
    platform: '小程序',
    batch: '202606-A',
    orderMethod: '家长',
    parentName: '刘家长',
    parentMobile: '133****1196',
    dealerReferrer: '--',
    courseType: '体验课',
    studentName: '刘同学',
    channel: '渠道推广',
    courseName: '高中英语体验课',
    amount: '¥ 99',
    paidAmount: '¥ 99',
    paymentTransactionNo: '20260626****8992',
    logisticsNo: '--',
    allocationStatus: '已分配',
    deliveryCenter: '总部交付中心',
    hasPad: '否',
    firstPurchase: '是',
    orderTime: '2026-06-26 15:48',
    orderRemark: '--',
    riskStatus: '--',
    afterSaleStatus: '--',
    nextAction: '查看详情',
    history: [{ time: '18:20', title: '体验课已完成', detail: '已提交课堂评价' }]
  },
  {
    id: 'order-7',
    orderNo: 'ZL52758783840709',
    status: '已支付',
    dealer: '总部直营',
    seller: '总部商城',
    orderingDealer: '--',
    plannerRequirement: '不需要',
    source: '线上订单',
    platform: '小程序',
    batch: '202606-A',
    orderMethod: '家长',
    parentName: '李家长',
    parentMobile: '181****5639',
    dealerReferrer: '--',
    courseType: '正式课',
    studentName: '李同学',
    channel: '线上商城',
    courseName: '初中数学正式课 20 课时',
    amount: '¥ 399',
    paidAmount: '¥ 399',
    paymentTransactionNo: '20260626****0709',
    logisticsNo: '--',
    allocationStatus: '已分配',
    deliveryCenter: '华北交付中心',
    hasPad: '否',
    firstPurchase: '否',
    orderTime: '2026-06-26 14:17',
    orderRemark: '家长提交退货申请',
    riskStatus: '--',
    afterSaleStatus: '退款中',
    nextAction: '审核退款',
    history: [{ time: '16:10', title: '提交退款申请', detail: '等待售后审核' }]
  }
]

export const deliverySeed = [
  {
    id: 'delivery-1',
    student: '陈同学',
    studentNo: 'ST2606270188',
    studentName: '陈同学',
    parentName: '陈家长',
    parentMobile: '138****2817',
    mobile: '138****2817',
    grade: '高中一年级',
    subject: '数学',
    stage: '正式课',
    courseName: '高中数学正式课 40 课时',
    subjectProduct: '高中数学正式课',
    deliveryCenter: '总部交付中心',
    teacherName: '--',
    className: '一对一',
    teachingMode: '一对一',
    deliveryMode: '线上',
    totalHours: '40',
    scheduledHours: '0',
    consumedHours: '0',
    remainingHours: '40',
    reservedHours: '0',
    evaluationStatus: '未评价',
    planner: '待分配',
    status: '待分配',
    deadline: '今天 14:00',
    owner: '交付一组',
    issue: '等待 3 小时',
    orderNo: 'ZL52809199884812',
    preferredTime: '工作日 14:00 - 18:00',
    history: [
      { time: '10:02', title: '进入教师分配队列', detail: '总部交付中心 · 数学' },
      { time: '09:46', title: '学员信息已确认', detail: '高中一年级 · 正式课' }
    ]
  },
  {
    id: 'delivery-2',
    student: '张同学',
    studentNo: 'ST2606270189',
    studentName: '张同学',
    parentName: '张家长',
    parentMobile: '186****0932',
    mobile: '186****0932',
    grade: '初中二年级',
    subject: '英语',
    stage: '体验课',
    courseName: '初中英语体验课',
    subjectProduct: '初中英语体验课',
    deliveryCenter: '总部交付中心',
    teacherName: '王老师',
    className: '一对一',
    teachingMode: '一对一',
    deliveryMode: '线上',
    totalHours: '1',
    scheduledHours: '0',
    consumedHours: '0',
    remainingHours: '1',
    reservedHours: '1',
    evaluationStatus: '未评价',
    planner: '王老师',
    status: '待排课',
    deadline: '今天 16:00',
    owner: '王老师',
    issue: '已匹配教师',
    orderNo: 'ZL52805925401750',
    preferredTime: '今天 16:00',
    history: [{ time: '10:18', title: '已匹配王老师', detail: '等待确认首次上课时间' }]
  },
  {
    id: 'delivery-3',
    student: '王同学',
    studentNo: 'ST2606270190',
    studentName: '王同学',
    parentName: '王家长',
    parentMobile: '150****6721',
    mobile: '150****6721',
    grade: '高中二年级',
    subject: '物理',
    stage: '正式课',
    courseName: '高中物理正式课 60 课时',
    subjectProduct: '高中物理正式课',
    deliveryCenter: '华东交付中心',
    teacherName: '陆老师',
    className: '线下一对一',
    teachingMode: '一对一',
    deliveryMode: '线下',
    totalHours: '60',
    scheduledHours: '1',
    consumedHours: '0',
    remainingHours: '60',
    reservedHours: '1',
    evaluationStatus: '未评价',
    planner: '陆老师',
    status: '时间冲突',
    deadline: '今天 15:30',
    owner: '交付二组',
    issue: '教师时间冲突',
    orderNo: 'ZL52804736554803',
    preferredTime: '今天 15:30',
    history: [
      { time: '10:26', title: '检测到排课冲突', detail: '原教师已有同时间课程' },
      { time: '09:52', title: '提交首次排课', detail: '今天 15:30 · 线上授课' }
    ]
  },
  {
    id: 'delivery-4',
    student: '赵同学',
    studentNo: 'ST2605200096',
    studentName: '赵同学',
    parentName: '赵家长',
    parentMobile: '177****4380',
    mobile: '177****4380',
    grade: '初中三年级',
    subject: '数学',
    stage: '正式课',
    courseName: '初中数学正式课 40 课时',
    subjectProduct: '初中数学正式课',
    deliveryCenter: '总部交付中心',
    teacherName: '周老师',
    className: '初三数学 A 班',
    teachingMode: '小班课',
    deliveryMode: '线上',
    totalHours: '40',
    scheduledHours: '20',
    consumedHours: '18',
    remainingHours: '22',
    reservedHours: '2',
    evaluationStatus: '已评价',
    planner: '周老师',
    status: '交付中',
    deadline: '周六 10:00',
    owner: '周老师',
    issue: '进度正常',
    orderNo: 'ZL52792542283656',
    preferredTime: '周六 10:00',
    history: [{ time: '昨天 21:02', title: '完成第 18 次消课', detail: '剩余 22 课时' }]
  },
  {
    id: 'delivery-5',
    student: '周同学',
    studentNo: 'ST2604180032',
    studentName: '周同学',
    parentName: '周家长',
    parentMobile: '159****9074',
    mobile: '159****9074',
    grade: '小学六年级',
    subject: '语文',
    stage: '正式课',
    courseName: '小学语文正式课 30 课时',
    subjectProduct: '小学语文正式课',
    deliveryCenter: '华东交付中心',
    teacherName: '苏老师',
    className: '小升初冲刺班',
    teachingMode: '小班课',
    deliveryMode: '线上',
    totalHours: '30',
    scheduledHours: '28',
    consumedHours: '28',
    remainingHours: '2',
    reservedHours: '0',
    evaluationStatus: '已评价',
    planner: '苏老师',
    status: '待续课',
    deadline: '07-01 前',
    owner: '苏老师',
    issue: '剩余 2 课时',
    orderNo: 'XL2606260091',
    preferredTime: '每周三 19:00',
    history: [{ time: '06-27 20:30', title: '续课预警', detail: '剩余课时低于 3' }]
  },
  {
    id: 'delivery-6',
    student: '刘同学',
    studentNo: 'ST2606260068',
    studentName: '刘同学',
    parentName: '刘家长',
    parentMobile: '133****1196',
    mobile: '133****1196',
    grade: '高中一年级',
    subject: '英语',
    stage: '体验课',
    courseName: '高中英语体验课',
    subjectProduct: '高中英语体验课',
    deliveryCenter: '总部交付中心',
    teacherName: '陈老师',
    className: '一对一',
    teachingMode: '一对一',
    deliveryMode: '线上',
    totalHours: '1',
    scheduledHours: '1',
    consumedHours: '1',
    remainingHours: '0',
    reservedHours: '0',
    evaluationStatus: '未评价',
    planner: '陈老师',
    status: '待评价',
    deadline: '今天 20:00',
    owner: '陈老师',
    issue: '课程已结束',
    orderNo: 'ZL52780547298992',
    preferredTime: '今天 20:00',
    history: [{ time: '18:20', title: '体验课已完成', detail: '等待家长评价' }]
  }
]

export const partnerSeed = [
  {
    id: 'partner-1',
    company: '杭州青禾教育',
    entityType: '有限公司',
    contact: '陈**',
    mobile: '138****1024',
    region: '浙江 / 杭州',
    address: '杭州市西湖区文三路 188 号',
    submittedAt: '今天 09:40',
    status: '待初审',
    risk: '低',
    completeness: 100,
    applicationNo: 'HZ2606270048',
    licenseNo: '9133********2048',
    licenseExpiresAt: '2029-05-16',
    accountStatus: '待开通',
    contractStatus: '待签约',
    reviewer: '合作中心',
    history: [
      { time: '09:42', title: '系统完成资料预检', detail: '4 项资料齐全，未发现主体风险' },
      { time: '09:40', title: '商家提交入驻申请', detail: '申请编号 HZ2606270048' }
    ]
  },
  {
    id: 'partner-2',
    company: '成都星途成长中心',
    entityType: '个体工商户',
    contact: '刘**',
    mobile: '186****7783',
    region: '四川 / 成都',
    address: '成都市高新区天府三街 88 号',
    submittedAt: '今天 08:15',
    status: '待补充',
    risk: '中',
    completeness: 72,
    applicationNo: 'CD2606270031',
    licenseNo: '9251********0031',
    licenseExpiresAt: '2027-08-03',
    accountStatus: '未开通',
    contractStatus: '资料待补充',
    reviewer: '合作中心',
    history: [{ time: '08:18', title: '资料预检未通过', detail: '合作协议缺少签章页' }]
  },
  {
    id: 'partner-3',
    company: '合肥未来课堂',
    entityType: '有限公司',
    contact: '王**',
    mobile: '159****3611',
    region: '安徽 / 合肥',
    address: '合肥市蜀山区潜山路 168 号',
    submittedAt: '昨天 17:20',
    status: '复审中',
    risk: '低',
    completeness: 100,
    applicationNo: 'HF2606260097',
    licenseNo: '9134********0097',
    licenseExpiresAt: '2028-11-22',
    accountStatus: '待开通',
    contractStatus: '待生效',
    reviewer: '合作负责人',
    history: [{ time: '昨天 18:02', title: '初审通过', detail: '已提交负责人复审' }]
  },
  {
    id: 'partner-4',
    company: '武汉云启教育',
    entityType: '有限公司',
    contact: '赵**',
    mobile: '177****0442',
    region: '湖北 / 武汉',
    address: '武汉市洪山区珞喻路 268 号',
    submittedAt: '昨天 15:08',
    status: '证照预警',
    risk: '高',
    completeness: 88,
    applicationNo: 'WH2606260086',
    licenseNo: '9142********0086',
    licenseExpiresAt: '2026-07-10',
    accountStatus: '冻结待核验',
    contractStatus: '证照待更新',
    reviewer: '合作中心',
    history: [{ time: '昨天 15:11', title: '系统触发证照预警', detail: '营业执照将在 12 天后到期' }]
  },
  {
    id: 'partner-5',
    company: '苏州知行学堂',
    entityType: '有限公司',
    contact: '周**',
    mobile: '133****8920',
    region: '江苏 / 苏州',
    address: '苏州市工业园区星湖街 328 号',
    submittedAt: '06-25 10:30',
    status: '已通过',
    risk: '低',
    completeness: 100,
    applicationNo: 'SZ2606250022',
    licenseNo: '9132********0022',
    licenseExpiresAt: '2030-03-18',
    accountStatus: '已开通',
    contractStatus: '履约中',
    reviewer: '合作负责人',
    history: [{ time: '06-25 16:20', title: '入驻审核通过', detail: '已开通商家账号' }]
  }
]

export const purchaseSeed = [
  {
    id: 'purchase-1',
    purchaseNo: 'CG2606270018',
    purchaseType: '线上采购单',
    relatedOrder: 'ZL52804736554803',
    studentName: '王同学',
    parentName: '王家长',
    parentMobile: '150****6721',
    merchant: '总部商城',
    supplier: '智鹿科技供应链',
    product: 'iPad 学习套餐',
    specification: '10.9 英寸 / 128G',
    quantity: '1',
    amount: '¥ 7,400',
    paidAmount: '¥ 7,400',
    paymentStatus: '已付款',
    voucherNo: 'FK2606****0018',
    logisticsNo: '待发货',
    expectedAt: '07-01',
    owner: '供应链组',
    deadline: '今天 18:00',
    status: '待发货',
    nextAction: '登记物流',
    history: [{ time: '09:02', title: '采购单生成', detail: '关联正式课订单 ZL52804736554803' }]
  },
  {
    id: 'purchase-2',
    purchaseNo: 'XCG2606260049',
    purchaseType: '线下采购单',
    relatedOrder: '--',
    studentName: '--',
    parentName: '--',
    parentMobile: '--',
    merchant: '总部交付中心',
    supplier: '智鹿设备中心',
    product: '教学平板',
    specification: '10.9 英寸',
    quantity: '10',
    amount: '¥ 32,000',
    paidAmount: '¥ 16,000',
    paymentStatus: '待补凭证',
    voucherNo: '待补充',
    logisticsNo: '--',
    expectedAt: '07-02',
    owner: '财务组',
    deadline: '明天 10:00',
    status: '待付款',
    nextAction: '补充付款凭证',
    history: [{ time: '06-26 16:42', title: '线下采购单创建', detail: '首付款凭证待补充' }]
  },
  {
    id: 'purchase-3',
    purchaseNo: 'XCG2606270012',
    purchaseType: '线下采购单',
    relatedOrder: '--',
    studentName: '--',
    parentName: '--',
    parentMobile: '--',
    merchant: '华东交付中心',
    supplier: '启航教育物资',
    product: '高中数学纸质教材',
    specification: '学生版',
    quantity: '60',
    amount: '¥ 5,160',
    paidAmount: '¥ 5,160',
    paymentStatus: '已付款',
    voucherNo: 'FK2606****0012',
    logisticsNo: 'YT****9031',
    expectedAt: '06-30',
    owner: '采购组',
    deadline: '今天 17:00',
    status: '运输中',
    nextAction: '确认到货',
    history: [{ time: '10:18', title: '供应商已发货', detail: '预计 06-30 到货' }]
  },
  {
    id: 'purchase-4',
    purchaseNo: 'CG2606260066',
    purchaseType: '采购退供',
    relatedOrder: 'ZL52758783840709',
    studentName: '李同学',
    parentName: '李家长',
    parentMobile: '181****5639',
    merchant: '总部商城',
    supplier: '智鹿配件中心',
    product: '学习平板配件包',
    specification: '标准配件包',
    quantity: '1',
    amount: '¥ 220',
    paidAmount: '¥ 220',
    paymentStatus: '退款中',
    voucherNo: 'TK2606****0066',
    logisticsNo: '待回寄',
    expectedAt: '待确认',
    owner: '售后组',
    deadline: '今天 16:30',
    status: '采购退供',
    nextAction: '确认退供',
    history: [{ time: '06-26 14:22', title: '订单发起退款', detail: '同步生成采购退供单' }]
  }
]

export const settlementSeed = [
  {
    id: 'settle-1',
    billNo: 'JS2606270018',
    partner: '华东交付中心',
    period: '06/20 - 06/26',
    businessAmount: '¥ 236,900',
    receivableAmount: '¥ 0',
    payableAmount: '¥ 32,800',
    paidAmount: '¥ 0',
    amount: '¥ 32,800',
    diff: '¥ 0',
    invoiceStatus: '已收票',
    settlementStatus: '待确认',
    owner: '财务二组',
    createdAt: '06-27 08:00',
    relatedOrders: '86',
    status: '待确认',
    history: [{ time: '08:00', title: '账单生成', detail: '华东交付中心周结算账单' }]
  },
  {
    id: 'settle-2',
    billNo: 'JS2606270017',
    partner: '成都星途成长中心',
    period: '06/20 - 06/26',
    businessAmount: '¥ 86,400',
    receivableAmount: '¥ 18,420',
    payableAmount: '¥ 0',
    paidAmount: '¥ 18,100',
    amount: '¥ 18,420',
    diff: '¥ 320',
    invoiceStatus: '待开票',
    settlementStatus: '核对中',
    owner: '财务一组',
    createdAt: '06-27 08:00',
    relatedOrders: '28',
    status: '有差额',
    history: [{ time: '09:12', title: '发现结算差额', detail: '商家确认金额与系统账单差额 ¥ 320' }]
  },
  {
    id: 'settle-3',
    billNo: 'JS2606270016',
    partner: '总部交付中心',
    period: '06/20 - 06/26',
    businessAmount: '¥ 486,900',
    receivableAmount: '¥ 0',
    payableAmount: '¥ 56,900',
    paidAmount: '¥ 0',
    amount: '¥ 56,900',
    diff: '¥ 0',
    invoiceStatus: '已收票',
    settlementStatus: '待打款',
    owner: '财务二组',
    createdAt: '06-27 08:00',
    relatedOrders: '126',
    status: '待打款',
    history: [{ time: '昨天 18:30', title: '合作方已确认账单', detail: '等待财务打款' }]
  },
  {
    id: 'settle-4',
    billNo: 'JS2606270015',
    partner: '华南交付中心',
    period: '06/13 - 06/19',
    businessAmount: '¥ 168,200',
    receivableAmount: '¥ 0',
    payableAmount: '¥ 27,600',
    paidAmount: '¥ 27,600',
    amount: '¥ 27,600',
    diff: '¥ 0',
    invoiceStatus: '已收票',
    settlementStatus: '已完成',
    owner: '财务二组',
    createdAt: '06-20 08:00',
    relatedOrders: '64',
    status: '已完成',
    history: [{ time: '06-21 16:20', title: '打款完成', detail: '已完成华南交付中心周结算' }]
  }
]

export const transactionSplitSeed = [
  {
    id: 'split-1',
    orderNo: 'ZL52809199884812',
    transactionNo: '20260627****8621',
    studentName: '陈同学',
    partner: '杭州青禾教育',
    deliveryCenter: '--',
    paidAmount: '¥ 12,800',
    merchantShare: '¥ 0',
    deliveryCost: '¥ 0',
    hqGross: '¥ 0',
    refundFrozen: '¥ 12,800',
    auditDiff: '¥ 0',
    settlementBills: [],
    paymentCheck: '待人工核验',
    allocationCheck: '未分配',
    splitCheck: '冻结',
    billCheck: '未生成',
    transferCheck: '未触发',
    blocker: '支付渠道成功但订单仍为未支付',
    checkStatus: '待核验',
    status: '待核验',
    rule: '支付异常订单先冻结，核验到账并完成分单后释放分账',
    nextAction: '核验支付状态并分配交付中心'
  },
  {
    id: 'split-2',
    orderNo: 'ZL52805925401750',
    transactionNo: '20260627****1750',
    studentName: '张同学',
    partner: '华东渠道中心',
    deliveryCenter: '--',
    paidAmount: '¥ 99',
    merchantShare: '¥ 20',
    deliveryCost: '¥ 0',
    hqGross: '¥ 79',
    refundFrozen: '¥ 0',
    auditDiff: '¥ 0',
    settlementBills: [],
    paymentCheck: '已到账',
    allocationCheck: '未分配',
    splitCheck: '预估',
    billCheck: '未生成',
    transferCheck: '未触发',
    blocker: '缺少交付中心，暂不能生成交付成本',
    checkStatus: '待核验',
    status: '待核验',
    rule: '体验课渠道分成已预估，待分配交付中心后生成交付成本',
    nextAction: '分配交付中心并生成交付账单'
  },
  {
    id: 'split-3',
    orderNo: 'ZL52804736554803',
    transactionNo: 'OFFLINE-20260627-0038',
    studentName: '王同学',
    partner: '成都星途成长中心',
    deliveryCenter: '华东交付中心',
    paidAmount: '¥ 7,400',
    merchantShare: '¥ 1,480',
    deliveryCost: '¥ 3,700',
    hqGross: '¥ 2,220',
    refundFrozen: '¥ 0',
    auditDiff: '¥ 0',
    settlementBills: ['JS2606270017', 'JS2606270018'],
    paymentCheck: '已到账',
    allocationCheck: '已分配',
    splitCheck: '已拆分',
    billCheck: '已生成',
    transferCheck: '核对中',
    blocker: '--',
    checkStatus: '已核对',
    status: '已核对',
    rule: '正式课代下单：商家 20% / 交付 50% / 总部 30%',
    nextAction: '进入周结算确认'
  },
  {
    id: 'split-4',
    orderNo: 'ZL52792542283656',
    transactionNo: '20260626****3656',
    studentName: '赵同学',
    partner: '总部直营',
    deliveryCenter: '总部交付中心',
    paidAmount: '¥ 18,600',
    merchantShare: '¥ 0',
    deliveryCost: '¥ 11,160',
    hqGross: '¥ 7,440',
    refundFrozen: '¥ 0',
    auditDiff: '¥ 0',
    settlementBills: ['JS2606270016'],
    paymentCheck: '已到账',
    allocationCheck: '已分配',
    splitCheck: '已拆分',
    billCheck: '已生成',
    transferCheck: '待打款',
    blocker: '--',
    checkStatus: '已核对',
    status: '已核对',
    rule: '总部直营正式课：交付 60% / 总部 40%',
    nextAction: '等待交付中心确认账单'
  },
  {
    id: 'split-5',
    orderNo: 'ZL52780547298992',
    transactionNo: '20260626****8992',
    studentName: '刘同学',
    partner: '华南渠道中心',
    deliveryCenter: '总部交付中心',
    paidAmount: '¥ 99',
    merchantShare: '¥ 20',
    deliveryCost: '¥ 50',
    hqGross: '¥ 29',
    refundFrozen: '¥ 0',
    auditDiff: '¥ 0',
    settlementBills: ['JS2606270015'],
    paymentCheck: '已到账',
    allocationCheck: '已分配',
    splitCheck: '已拆分',
    billCheck: '已生成',
    transferCheck: '已完成',
    blocker: '--',
    checkStatus: '已核对',
    status: '已核对',
    rule: '体验课：渠道 ¥20 / 交付 ¥50 / 总部 ¥29',
    nextAction: '已进入账单归档'
  },
  {
    id: 'split-6',
    orderNo: 'ZL52758783840709',
    transactionNo: '20260626****0709',
    studentName: '李同学',
    partner: '总部直营',
    deliveryCenter: '华北交付中心',
    paidAmount: '¥ 399',
    merchantShare: '¥ 0',
    deliveryCost: '¥ 0',
    hqGross: '¥ 0',
    refundFrozen: '¥ 399',
    auditDiff: '¥ 0',
    settlementBills: [],
    paymentCheck: '已到账',
    allocationCheck: '已分配',
    splitCheck: '冻结',
    billCheck: '冲销待定',
    transferCheck: '未触发',
    blocker: '售后退款中，等待退款审核后冲销',
    checkStatus: '冻结',
    status: '冻结',
    rule: '售后退款中订单全额冻结，退款审核完成后冲销或重新分账',
    nextAction: '等待退款审核结果'
  }
]

export const analyticsRank = [
  { rank: 1, name: '华东交付中心', value: '¥ 268,400', trend: '+12.8%' },
  { rank: 2, name: '总部交付中心', value: '¥ 236,900', trend: '+9.4%' },
  { rank: 3, name: '华南交付中心', value: '¥ 189,200', trend: '+6.1%' },
  { rank: 4, name: '西南交付中心', value: '¥ 152,800', trend: '-1.8%' },
  { rank: 5, name: '华北交付中心', value: '¥ 128,600', trend: '+3.2%' }
]
